import type { Metadata } from 'next';

import Header from '@/ui/organisms/header';
import './globals.scss';
import { Pretendard } from './font';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={Pretendard.className}>
        <Header />
        { children }
      </body>
    </html>
  );
}
